"""empty message

Revision ID: d4a1b71a3549
Revises: 0d14c3f3ca6e
Create Date: 2024-01-22 18:19:51.116067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a1b71a3549'
down_revision = '0d14c3f3ca6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('year', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('features', sa.String(length=200), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('name')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('features')
        batch_op.drop_column('model')
        batch_op.drop_column('year')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
